import {Lalezar} from "next/font/google";
import "./globals.css";

const lalezar = Lalezar({
  weight: "400",
  subsets: ["latin"],

  variable: "--font-lalezar",
});

export const metadata = {
  title: "Universitydemo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lalezar.variable}>
        <main>
        {children}
        </main>
      </body>
    </html>
  );
}
